######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/logo-b.svg"
logo_on_black: "/img/logo-b.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]


github:
  repo_url: "https://github.com/deepcausality-rs/sites/web"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/deepcausality-rs/deep_causality"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""
